fields:
  generic-number:
    name: عدد معمولی
  grade:
    name: نمره
  attached-file:
    name: فایل ضمیمه
  faculty:
    name: دانشکده
    collection: [ علوم, علوم ریاضی, فنی, مهندسی هسته‌ای, لیزر, ادبیات, الهیات, ... ]
  major:
    name: رشته تحصیلی
    collection:
      علوم: [ فیزیک، شیمی ]
      'علوم ریاضی': [ ریاضی, آمار, علوم کامپیوتر ]
      فنی: [ مهندسی کامپیوتر, برق ]
  minor:
    name: گرایش
